### PR TITLE
Transfer ownership to openfun

### PR DESCRIPTION
**Pull request by regisb**
This plugin is about to change considerably in the way it is interfaced with
Tutor/Open edX. From now on, the plugin will be managed by the FUN-MOOC team.
In practical terms, it means that the following changes will occur:

- On pypi the plugin will be moved to "tutor-contrib-richie". The existing
  plugin will be kept for backward compatibility but upgrades will be available
  only in the contrib package. Thus, end users should uninstall tutor-richie
  before installing tutor-contrib-richie.
- The code repo will be moved from github.com/overhangio/tutor-richie to
  github.com/openfun/tutor-contrib-richie.
- The "richie" plugin will be removed from the list of default plugins that
  ship with `pip install tutor[full]` and the tutor binary. The plugin should
  then be manually installed from pypi (see above).

@sampaccoud if you :+1: this PR I'll rename the repo and the pypi package prior to merging the PR.

@BbrSofiane FYI.

### CODE REVIEW

**Comment by regisb** [comment]
@sampaccoud what are your thoughts on this?

**Comment by sampaccoud** [comment]
I was discussion with everybody and can now confirm: let's do it :rocket:

**Comment by regisb** [comment]
I'm going to temporarily need permission to create public repositories in the openfun organization. Can you grant me that @sampaccoud?

**Comment by sampaccoud** [comment]
@regisb I didn't see how to do this without adding you as admin on the whole organization. Maybe more direct that you add me as admin only on the repository so I can transfer it?

**Comment by sampaccoud** [comment]
All done! Thank you for your assistance @regisb

**Pull request merged**
